GRANT USAGE ON SCHEMA public TO oracle_ro;
GRANT USAGE ON SCHEMA public TO auth_ro;
GRANT USAGE ON SCHEMA public TO app_rw;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO oracle_ro;
REVOKE ALL ON TABLE public.users FROM oracle_ro;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM auth_ro;
GRANT SELECT ON TABLE public.users TO auth_ro;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_rw;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO app_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO oracle_ro;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app_rw;